---
  - name: nginx and php installation 
    apt:
      pkg: 
      - nginx
      - unzip
      - php7.4-zip
      - php-imagick
      - php7.4-curl
      - php7.4-fpm
      - php7.4-mbstring
      - php7.4-cli
      - php7.4-bcmath
      - php7.4-xml
      - php7.4-mysql
      - php7.4-common
      - php7.4-gd
      - php7.4-json
      update_cache: yes

  - name: nginx vhost configuration
    template :
      src: vhost.nginx.conf.j2
      dest: /etc/nginx/sites-enabled-default

  - name: wordpress project download and unzipping it
    ansible.builtin.unarchive:
      src: https://wordpress.org/latest.zip
      dest: /var/www/html
      remote_src: yes

  - name: configuring the wp-config file
    template: 
      src: wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php

  - name: change folder permission
    ansible.builtin.file:
      path: /var/www/html/wordpress
      owner: www-data
      group: www-data
      mode: '0755'

  - name: nginx restart 
    service:
      name: nginx
      state: restarted